### ISSUE TITLE
COME Utente VOGLIO Visualizzare lo stato del gioco IN MODO DA Poter prendere decisioni

### ISSUE THREAD

**Issue by MauroZorzin** [lta-unimib/progetto-risiko-1-risikiamo#1]
PREDECESSORS:
-
- #2 
- #7 

TASK : 
-
- Comunicare il turno hai giocatori
- Comunicare hai giocatori la stato della partita appena viene modificata
- Visualizare armate spostamenti e attacchi

**Comment by fraking00** [comment]
closed without a branch
