### ISSUE TITLE
COME Sistema VOGLIO Verificare il raggiungimento di un obiettivo IN MODO DA assegnare la vittoria a un giocatore

### ISSUE THREAD

**Issue by PmP-source** [lta-unimib/progetto-risiko-1-risikiamo#10]
PREDECESSORS:
-
- #3 
- Objective
- #2 

TASK:
-
- alla fine di ogni turno controllare lo stato degli obiettivi dei giocatori
- assegnare la vittoria al giocatore che l'ha raggiunto
- non controllare gli obiettivi dei giocatori arresi

**Comment by MauroZorzin** [comment]
Chiuso senza breach
