### ISSUE TITLE
COME Utente VOGLIO Ricevere i rinforzi IN MODO DA allocarli

### ISSUE THREAD

**Issue by Dadivargas** [lta-unimib/progetto-risiko-1-risikiamo#16]
PREDECESSORI:
-
- #2 
- #5 
- #42 
- #41 

TASK:
-
- Voglio ricevere un numero di armate in base al numero di territori che controllo diviso 3 per difetto
- Voglio ricevere un numero di armate in base al numero di continenti che possiedo
- Voglio ricevere un numero di armate in base alla combinazione di carte che possiedo
- Voglio ricevere 2 armate per ogni carta rinforzo riscattata raffigurante un territorio da me posseduto

**Comment by MauroZorzin** [comment]
- Completato senza Branch
