### ISSUE TITLE
COME Sistema VOGLIO avere una mappa IN MODO DA renderla interagibile

### ISSUE THREAD

**Issue by fraking00** [lta-unimib/progetto-risiko-1-risikiamo#19]
TASK
-
- Il Sistema rende visibile la mappa
- L'utente passando col mouse vede dove è
- L'utente selezione e deseleziona i territori a scelta

**Comment by fraking00** [comment]
La mappa è funzionante la ho testata e tutto, da revisionare da parte degli altri prima di mergiare.

**Comment by MauroZorzin** [comment]
Devi chiedere di mergare per poter chiedere la review
