### ISSUE TITLE
COME Sistema VOGLIO Consentire solo all'utente di turno di giocare IN MODO DA coordinare la partita

### ISSUE THREAD

**Issue by MauroZorzin** [lta-unimib/progetto-risiko-1-risikiamo#6]
PREDECESSORS:
-
- #2 
- #3 

TASK:
-
- Ordinare i Player
- Scorrere tra i Player in ordine
- Saltare Player Sconfitti o arresi
- Fermarsi se un Player vince

**Comment by PmP-source** [comment]
finito e passa i test aspetto review
